
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  patient VARCHAR(100) NOT NULL,
  amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'PAID',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
